# Generated by Django 6.0.3 on 2026-04-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='description',
            field=models.TextField(),
        ),
    ]
