# Generated by Django 6.0.3 on 2026-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_username'),
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dream',
            field=models.ManyToManyField(blank=True, to='dreams.dream'),
        ),
    ]
