# Generated by Django 6.0.3 on 2026-04-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_follow_count_user_follower_count_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow_count',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='follower_count',
            new_name='following_count',
        ),
    ]
