# Generated by Django 6.0.3 on 2026-04-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_follow_count_user_followers_count_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dreams', '0002_dream_slug_alter_dream_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='accounts_us_first_n_636bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='accounts_us_last_na_74deb2_idx'),
        ),
    ]
