# Generated by Django 6.0.3 on 2026-03-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='reactions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
