# Generated by Django 6.0.3 on 2026-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_dream_slug_alter_dream_description'),
        ('feeds', '0002_remove_feed_reactions_feed_comment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='dreams',
            field=models.ManyToManyField(related_name='feeds', to='dreams.dream'),
        ),
    ]
