# Generated by Django 6.0.3 on 2026-04-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_feed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='visibility',
            field=models.CharField(choices=[('PR', 'private'), ('PL', 'public'), ('PT', 'protected')]),
        ),
    ]
